:filetype plugin on
:syntax off
" Turn tabs into spaces
:set expandtab
:set ts=4
" Align wrapped lines to indent of original line
:set breakindent
" Highlight search
:set hlsearch
" Show searches as they are found
:set incsearch
" Do not redraw screen in between macros
:set lazyredraw
" Shows matching braces
:set showmatch
" Shows line number and file location % in bottom-right
:set ruler
" Nocompat
:set nocp
" Show commmand
:set sc

:colorscheme colors
"
" Keybindings
"

" Emacs-like move to start/end of line in insert mode
map <C-e> <esc>$
map <C-a> <esc>0
" Emacs-like delete to end (without copying to a register)
map <C-k> "_d$

" Quick exits
map zz :q!<cr>
map zx :wq<cr>

" Space to quick save
nmap <Space> :w<cr>

" Shift-tab is escape in insert mode
imap <S-TAB> <Esc>
