:filetype plugin on
:syntax off
:set expandtab
:set ts=4
:set breakindent
:set hlsearch
:set incsearch
:set lazyredraw
:set showmatch
:set foldenable
:set foldlevelstart=20

" Fold/unfold with space
nnoremap <space> za

:colorscheme colors

:function CommentedFileReader()
    :hi Normal ctermbg=DarkGrey
    :hi LineNr ctermfg=Cyan
    :hi ColorColumn ctermbg=Yellow
:endfunction

:function CommentedFileReader_Undo()
    :hi Normal ctermbg=None
    :hi LineNr ctermfg=DarkBlue
    :hi ColorColumn ctermbg=Yellow
:endfunction

" Keybindings

imap <C-e> <esc>$a
imap <C-a> <esc>0i

map zz :q!<cr>
map zx :wq<cr>

map <C-k> "_dd
