:filetype plugin on
:syntax off
:set expandtab
:set ts=4
:set breakindent
:set hlsearch
:set incsearch
:set lazyredraw
:set showmatch
:set foldenable
:set foldlevelstart=20

:colorscheme colors

:function CommentedFileReader()
    :hi Normal ctermbg=DarkGrey
    :hi LineNr ctermfg=Cyan
    :hi ColorColumn ctermbg=Yellow
:endfunction

:function CommentedFileReader_Undo()
    :hi Normal ctermbg=None
    :hi LineNr ctermfg=DarkBlue
    :hi ColorColumn ctermbg=Yellow
:endfunction

" Keybindings

" Emacs-like move to start/end of line in insert mode
imap <C-e> <esc>$a
imap <C-a> <esc>0i

" Quick exists
map zz :q!<cr>
map zx :wq<cr>

" Delete line without copying it to a register
map <C-k> "_dd
