#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

. /usr/local/etc/.bash_aliases
. /usr/share/git/completion/git-completion.bash
. /usr/share/git/completion/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=1 #This shows dirty/clean status on the git prompt

alias code='cd /home/zaraksh/Documents/Code'
alias svim='sudoedit'
alias open='xdg-open'

tmp() {
	rand=$RANDOM
	mkdir /tmp/$rand-mktmp
	ln -s /tmp/$rand-mktmp .
    cd ./$rand-mktmp
}

PS1='[\u@\h \w]$(__git_ps1 "  (%s)")_ '

# This allows gpg signing for git
export GPG_TTY=$(tty)
